### ISSUE TITLE
I want to extract clips from videos? How should I do? Thanks

### ISSUE THREAD

**Issue by dengyang1** [arpane4c5/ActivityNet#1]

**Comment by arpane4c5** [comment]
Well, if you are looking for a direct function that does that in this repository, you won't find one. But there are a number of ways that you can modify the code and use parts of it to create a set of functions that does the job. One way would be create a function (similar to get_optical_flow_vid() in file optical_flow.py) that takes the video path, temporal localization parameters of segments, destination path for clips etc. and calls it for all the required videos that you want to extract clips for. This method could also be called in a parallel fashion. 
I hope this helps.

**Comment by arpane4c5** [comment]
Closing !
